//90
// 
// This code was generated by a tool. Any manual changes will be lost
// the next time this code is regenerated, change VersionInfo.tt instead.

using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyCompany("Afreet Software, Inc.")]
[assembly: AssemblyProduct("VE3NEA.HamCockpit")]
[assembly: AssemblyCopyright("Copyright © Afreet Software, Inc. 2020")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: ComVisible(false)]

//increment manually when releasing a new version
//not shown in the file properties dialog 
[assembly: AssemblyVersion("1.0")]

//increment after every build
//appears in file properties as File Version and Product Version
[assembly: AssemblyFileVersion("1.0.4.90")]

//Product Version shows AssemblyInformationalVersion if present,
//otherwise it shows AssemblyFileVersion